"""empty message

Revision ID: 38d69d585c22
Revises: ca35bdb74039
Create Date: 2017-03-02 00:05:29.696414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d69d585c22'
down_revision = 'ca35bdb74039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followers_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followers_timestamp'))

    op.drop_table('followers')
    # ### end Alembic commands ###
