"""empty message

Revision ID: 440a41658336
Revises: 
Create Date: 2017-02-25 13:48:04.759363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440a41658336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recs', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
