"""empty message

Revision ID: 583e31ce8f93
Revises: 
Create Date: 2017-03-11 20:45:38.144789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583e31ce8f93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recs', sa.Column('made_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recs', 'made_private')
    # ### end Alembic commands ###
