"""empty message

Revision ID: 5e2a295c9306
Revises: 583e31ce8f93
Create Date: 2017-03-12 14:58:44.556464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2a295c9306'
down_revision = '583e31ce8f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'verified')
    # ### end Alembic commands ###
