"""empty message

Revision ID: 9fbf3a85205e
Revises: 5e2a295c9306
Create Date: 2017-03-12 20:35:04.744581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbf3a85205e'
down_revision = '5e2a295c9306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recmoderations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_by', sa.Integer(), nullable=True),
    sa.Column('mod_on', sa.Integer(), nullable=True),
    sa.Column('action', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mod_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mod_on'], ['recs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commoderations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_by', sa.Integer(), nullable=True),
    sa.Column('mod_on', sa.Integer(), nullable=True),
    sa.Column('action', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mod_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mod_on'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commoderations')
    op.drop_table('recmoderations')
    # ### end Alembic commands ###
