"""empty message

Revision ID: b629b9b4d864
Revises: 9fbf3a85205e
Create Date: 2017-03-12 20:46:30.481430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b629b9b4d864'
down_revision = '9fbf3a85205e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commoderations', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('recmoderations', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recmoderations', 'timestamp')
    op.drop_column('commoderations', 'timestamp')
    # ### end Alembic commands ###
