"""empty message

Revision ID: b64a376b2248
Revises: b629b9b4d864
Create Date: 2017-03-14 12:59:40.554958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64a376b2248'
down_revision = 'b629b9b4d864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('verification', sa.Integer(), nullable=True))
    op.drop_column('comments', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('verified', sa.BOOLEAN(), nullable=True))
    op.drop_column('comments', 'verification')
    # ### end Alembic commands ###
