"""empty message

Revision ID: ca35bdb74039
Revises: 440a41658336
Create Date: 2017-02-25 18:17:55.964524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca35bdb74039'
down_revision = '440a41658336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invalid_logins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('invalid_logins')

    # ### end Alembic commands ###
