"""empty message

Revision ID: e38a8a08e610
Revises: 38d69d585c22
Create Date: 2017-03-09 01:20:21.106364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38a8a08e610'
down_revision = '38d69d585c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_by_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_by_user', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['comment_by_user'], ['username'])

    # ### end Alembic commands ###
