"""empty message

Revision ID: e9e44e7390ed
Revises: 99c69ad59e21
Create Date: 2017-03-25 13:50:05.895161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e44e7390ed'
down_revision = '99c69ad59e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apirequests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('requester', sa.INTEGER(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('role', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['requester'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apirequests_timestamp'), 'apirequests', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apirequests_timestamp'), table_name='apirequests')
    op.drop_table('apirequests')
    # ### end Alembic commands ###
